exp_path: "/home/trojan/Desktop/curve/MAPF-LNS2/maps"
ins_num: 25
time_limit: 60
plot_ci: true

f_weights:
  - 1.01
  - 1.02
  - 1.05
  - 1.10

maps:

  - name: den520d
    label: den520d
    scens:
      - even
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800


  - name: warehouse-20-40-10-2-1
    label: warehouse
    scens:
      - even
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800

  - name: maze-32-32-2
    label: maze
    scens:
      - even
      - random
    num_of_agents:
      - 10
      - 20
      - 30
      - 40
      - 50

  - name: room-32-32-4
    label: room
    scens:
      - even
      - random
    num_of_agents:
      - 10
      - 20
      - 30
      - 40
      - 50

  - name: random-32-32-20
    label: random
    scens:
      - even
      - random
    num_of_agents:
      - 20
      - 40
      - 60
      - 80
      - 100

  - name: empty-32-32
    label: empty
    scens:
      - even
      - random
    num_of_agents:
      - 100
      - 200
      - 300
      - 400
      - 500

solvers:
  - name: EECBS0
    label: 'EECBS+'
    color: 'grey'
    marker: 'P'
    w: 1.02
    mtth: -1
    T_N: -1
    T_i: -1
