exp_path: "/home/trojan/Desktop/curve/MAPF-LNS2"
ins_num: 25
time_limit: 60
plot_ci: true

f_weights:
  - 1.01
  - 1.02
  - 1.05
  - 1.10

maps:

  - name: random-32-32-20
    label: random
    scens:
      - even
      - random
    num_of_agents:
      - 20
      - 40
      - 60
      - 80
      - 100

  - name: den520d
    label: den520d
    scens:
      - random
      - even
    num_of_agents:
      - 200
      - 400
      - 600
      - 800


  - name: warehouse-20-40-10-2-1
    label: warehouse
    scens:
      - random
      - even
    num_of_agents:
      - 200
      - 400
      - 600
      - 800

solvers:
  - name: GRID.csv-LNS
    label: 'GRID+'
    color: 'grey'
    marker: 'P'
    w: 1.02
    mtth: -1
    T_N: -1
    T_i: -1
